services:
  db:
    image: postgres:latest
    restart: always
    container_name: sdb1-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sdb1-pgadmin
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    
volumes:
  postgres-data:
  pgadmin-data:
